### ISSUE TITLE
I've been rickrolled!

### ISSUE THREAD

**Issue by TechStudent10** [rick/roll#3]
oof

**Comment by rick** [comment]
Your heart's been aching but you're too shy to say it

**Comment by TechStudent10** [comment]
Inside we both know what's been, going on.

**Comment by sophuric** [comment]
you know the game and we're gonna play it
aaaaand if you ask me how i'm feeling,

**Comment by sophuric** [comment]
don't tell me you're too blind to see

**Comment by TechStudent10** [comment]
@mekb-turtle the next lyrics is "You know the game and we're, gonna play it!" then "Aaaaaaaand if you ask me how I'm feeling. Don't tell me you're too, blind to see!".

**Comment by TechStudent10** [comment]
Never Gonna Give You Up!

**Comment by sophuric** [comment]
yeah i can't memorize everything lul

**Comment by TechStudent10** [comment]
yeah
