### ISSUE TITLE
Where is my free bobux?

### ISSUE THREAD

**Issue by yeetyboi56-deprecated** [rick/roll#4]
Where is my free bobux?

**Comment by sophuric** [comment]
disappeared like my father went to get the milk

**Comment by yeetyboi56-deprecated** [comment]
> disappeared like my father went to get the milk

give me free bobux !!!1111!!1

**Comment by sophuric** [comment]
no

**Comment by yeetyboi56-deprecated** [comment]
o em gee scemer !!111!!11!11!

**Comment by sophuric** [comment]
wtf does robux have to do with a rickroll?

**Comment by yeetyboi56-deprecated** [comment]
i was told i will get free bobux if i click here

**Comment by yeetyboi56-deprecated** [comment]
gib bobux !111!!!!!11

**Comment by sophuric** [comment]
shut

**Comment by yeetyboi56-deprecated** [comment]
ratio

**Comment by sophuric** [comment]
stop you're giving me notifications
